### ISSUE TITLE
Implement InMemoryTodoListRepository

### ISSUE THREAD

**Issue by Igorbek** [yuriyoleynikov/MVCApp#2]
Define and implement the following interface:

``` cs
public interface ITodoListRepository {
  IEnumerable<TodoItem> GetTodoListByUser(string userId);
  void DeleteItem(Guid itemId);
  void AddItem(string userId, TodoItem item);
}
```

It requires to create:
- [ ] `TodoItem` model (use `Guid Id` as an identifier of the item)
- [ ] `InMemoryTodoListRepository` class which implements `ITodoListRepository`

As a backing storage a `List<T>` can be used.

**Comment by yuriyoleynikov** [comment]
TodoItem => TodoItemModel
